### ISSUE TITLE
通过TxUtility.ClientToTransferAccount签名异常

### ISSUE THREAD

**Issue by LmingXie** [WisedomChainGroup/java-sdk#1]
问题：通过TxUtility.ClientToTransferAccount签名异常

参数：原生WDC签名参数 pubkeyHash：1c33e5d8adde0cf3cc52c7505468e79586a46688，to：f86bc09b6f33536dfa6641b7702d0dafa1112cb5,value：1，prikeyStr：e29431161d1e91e141c24244490b4479e2c40c36783fc08ea5b86c1ed67be921，nonce：0 

签名结果：{"message":"事务构造有问题","statusCode":5000} 

异常信息：java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.company.keystore.util.ByteUtil.bytearraycopy(ByteUtil.java:86)
	at com.company.keystore.wallet.TxUtility.ClientToTransferAccount(TxUtility.java:537)
	at com.company.Main.sign(Main.java:52)
	at com.company.Main.main(Main.java:25)

**Comment by Zephyr-tech-afk** [comment]
第一个参数填公钥，不是公钥哈希
